### ISSUE TITLE
Can't start with PHP

### ISSUE THREAD

**Issue by davidcetinkaya** [palmenhq/nymbframework#2]
I know PHP, so what problemo is it?

```php
$my_nymb = 🥵;
```

**Comment by palmenhq** [comment]
try `sudo apt-get remove php && sudo apt-get install openjdk8`

**Comment by davidcetinkaya** [comment]
### Wow! You just helped me decide what to have for lunch.

You're awesome, thank you 🎉!

**Comment by palmenhq** [comment]
Amazing, enjoy! 🍽
